basePath: /api/v1
definitions:
  entity.Product:
    properties:
      description:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: waldrey22@gmail.com
    name: Waldrey Souza Silva
    url: http://waldrey.com/
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  title: Eulabs Products API
  version: "1.0"
paths:
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: Get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Product'
            type: array
      summary: List products
      tags:
      - products
  /api/v1/products/:id:
    delete:
      consumes:
      - application/json
      description: Deletes the product from the system
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Get product by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Product'
            type: array
      summary: Get Product
      tags:
      - products
    patch:
      consumes:
      - application/json
      description: Update product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Product'
            type: array
      summary: Update product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Product'
            type: array
      summary: Update product
      tags:
      - products
swagger: "2.0"
